apiVersion: v1

kind: Service

metadata:
  name: tasbih-service

spec:
  type: NodePort

  selector:
    app: tasbih

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
